### ISSUE TITLE
Add setup for Google Analytics

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#118]
# Description

We want to collect basic analytics using Google Analytics.

# Tasks

- [x] Have an env var for adding a Google Analytics code: `GOOGLE_ANALYTICS_CODE`
- [x] If the env var is populated, load the Google Analytics script at bottom of body of all templates
- [ ] Setup Open Trials production instance with `GOOGLE_ANALYTICS_CODE`
- [ ] Functional test

**Comment by vitorbaptista** [comment]
@pwalsh The code for this was merged, we just need a Google Analytics ID now. Could you create one with whatever Google account suits best and post its ID here? Also, please give me admin permissions on it.

**Comment by vitorbaptista** [comment]
Done :+1:
