### ISSUE TITLE
Integrate OKI Panel Bar and Cookie Bar

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#121]
# Description

As with most OKI properties, integrate the Panel and the Cookie Bar.

# Tasks

- [x] Add OKI Panel ( http://a.okfn.org/html/oki/panel/ )
  - [x] Shift the existing menu to the left some amount so the panel does not cover it
- [x] Add Cookie Bar ( http://a.okfn.org/html/oki/cookie-bar/ )
  - [x] Only show cookie bar if google analytics is set

**Comment by smth** [comment]
- OKI Panel is added, with slight menu layout changes to accommodate it. 
- The cookie bar is added in [this branch](https://github.com/opentrials/opentrials/tree/cookie-bar), but currently is not dependant on Google Analytics (there is no Google Analytics). Not sure if should be merged as is.

**Comment by pwalsh** [comment]
DONE.
