### ISSUE TITLE
Fix main navigation

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#122]
# Description

Requires https://github.com/opentrials/opentrials/issues/121

# Tasks

- [ ] Search: rename to "Explore" and remove the icon
- [ ] Login: inline with other nav items
- [ ] Order of nav items:` Explore | About | Login [OKI PANEL]`

<img width="330" alt="screenshot 2016-05-16 19 21 22" src="https://cloud.githubusercontent.com/assets/791678/15296011/082de086-1b9c-11e6-82dc-41ab96f2d542.png">

**Comment by pwalsh** [comment]
@smth my suggestion for inlining login is just because I'm not sure how it will work with the OKI Panel. However, you will have a solution for this, so, go ahead with any solution you prefer of course.
