### ISSUE TITLE
UI when linking to related entities

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#124]
# Description

Requires #142 

We've stubbed out detail pages for different entities in the database. These entities are always linked to one, or many, trials, and the user gets to these pages via a trial detail page, at present.

As the database grows and more data is cleaned and normalised, these entities will get more information, be de-duped and matched better, and so on.

As each view in the OpenTrials explorer is also kind of a "call to action" to enrichment/add data to the system, we want to use these pages as, not only an opportunity to see what data we currently have, but also to invite visitors to share additional data that may be related to the currently viewed entity.

Currently, we just have some basic pages that were stubbed out. Below, we detail a pattern for these "related entity pages", to inform the UI.

# Tasks

For each of:

- Person ( example: http://explorer.opentrials.net/persons/3b4f3ee7-fb08-486e-81ce-a11ce0746a6e )
- Organisation ( example: http://explorer.opentrials.net/organisations/563394ab-fb59-4efe-89ba-854808627a84 )
- Intervention ( example: http://explorer.opentrials.net/interventions/3349eef9-ccaf-4bae-bc16-2bbf26f86217 )
- Condition ( example: http://explorer.opentrials.net/conditions/46170876-6591-4260-929d-48669b3fb2b7 )

#### Page elements

- [x] Title ({NAME})
- [ ] Other fields that come on the actual record? Have to inspect the record
- [x] If no other fields, a snippet under title that says something like "We do not have any more information on {NAME}. If you do, please <a href="{contribute_link}">contribute some data</a>"
- [x] Under other fields (or, the no data snippet), a section with a selection of search results. An example given below. The search results are available in the template as `searchResults`
- [x] Under the search fields a section titled "More results", with "OpenTrials has `searchCount` results for this {TYPE}. See all" going to a full search page, and "Search for this {TYPE} on Google"
- [x] Sidebar with "download json" and "contribute data" actions
- [x] Implemented in HTML via PR

#### Result snippet

```
<h2>Most recent trials for {NAME}</h2>
# for result in search_results
    # a list of search results, probably a small, minified version of the main results - just with title and date fields or something
# end for
```

**Comment by pwalsh** [comment]
Duplicates #131

**Comment by vitorbaptista** [comment]
For the "More results" search link, you must generate an URL like `/search?person=Sylvia+Wilson%2C+MD` (try adding the filter manually in the search page, so you can see which param relates to which entity)

To see what data each entity has available, check:
* http://api.opentrials.net/v1/persons/3b4f3ee7-fb08-486e-81ce-a11ce0746a6e
* http://api.opentrials.net/v1/organisations/511ba3f1-a5bf-4aed-a4c2-85ac815b9ba1
* http://api.opentrials.net/v1/interventions/3349eef9-ccaf-4bae-bc16-2bbf26f86217
* http://api.opentrials.net/v1/conditions/46170876-6591-4260-929d-48669b3fb2b7

**Comment by smth** [comment]
I think I've done about as much as I can [here](https://github.com/opentrials/opentrials/commit/a36814ac8878f8dfada541fe719bbce647ce4ecb).

I have hard-coded the "We do not have any more information" text, as it seems to me that there is no data at the moment.

The count for "More results" is currently the same one used for the "recent" results.

The download link needs to be added (I don't know what it is).

**Comment by vitorbaptista** [comment]
The download link is simply a link to the API (e.g. http://api.opentrials.net/v1/persons/3b4f3ee7-fb08-486e-81ce-a11ce0746a6e)

About having more data, you're right. The only thing we have for these entities is their name.

**Comment by smth** [comment]
OK, so is there a variable available to the template for that? Or for the base of the API URL at least?

**Comment by vitorbaptista** [comment]
@smth I've just added an `url` attribute to each entity. This is now deployed on staging, check http://api.next.opentrials.net/v1/search

This change should make it easier for you :+1:

**Comment by pwalsh** [comment]
DONE
