### ISSUE TITLE
Implement collector for HRA data

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#128]
# Description

HARP ( https://www.harp.org.uk/ ) has research summaries for a range of clinical trials. These research summaries can be extracted, cached in our warehouse (what a collector does), and then later processed to match on trials and prepare for exposing via the public Database/API (what a processor does: has a distinct task https://github.com/opentrials/opentrials/issues/138).

There are some particularities to the usage of the HARP API, these are documented in a reference file we have been provided (currently private). These particularities may inform the way we collect and update our warehouse collection of HRA data.

## Existing collectors for API-based data sources

FYI if helpful to reference.

- https://github.com/opentrials/collectors/tree/master/collectors/icdcm
- https://github.com/opentrials/collectors/tree/master/collectors/fdadl
- https://github.com/opentrials/collectors/tree/master/collectors/icdpcs

# Tasks

- [x] Implement `collect` interface to request Research Summary data from HARP
- [x] Write the logic to deal with the API restrictions (day range for queries)
- [x] Write logic for updating (when we have data in the table)
- [x] Populate warehouse table with the data
- [x] Write tests

@roll specifically about how we implement with the restrictions, you may have to guide @BenGosub here a bit. Also, if my task list is incomplete or vague, please help me tweak it :).

**Comment by roll** [comment]
@BenGosub 
marked `updating logic` as done because it's part of the collecting framework when you use `Pipeline.write_item`

**Comment by pwalsh** [comment]
@roll great to know! That is one for docs/blog post :)

**Comment by BenGosub** [comment]
@roll I notice I've made a mistake in the authorization sting, which after correction returns HTTP/1.1" 500 661 (Internal Server Error)
Headers:
{'Authorization': 'Basic T3BlbnRyaWFscy10ZWFtQG9rZm4ub3JnCjpScFhHTHMzeE5mUDhGOWZO==', 'Connection': 'keep-alive', 'Accept-Encoding': 'gzip, deflate', 'Accept': '/', 'User-Agent': 'python-requests/2.10.0'}
URL:
https://stage.harp.org.uk/HARPApiExternal/api/ResearchSummaries?datePublishedFrom=2015-01-01&datePublishedTo=2015-12-31&updatesFilter=1

Output:

INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): stage.harp.org.uk
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/logging/handlers.py", line 863, in emit
    self.socket.sendto(msg, self.address)
gaierror: [Errno -2] Name or service not known
Logged from file connectionpool.py, line 788
DEBUG:requests.packages.urllib3.connectionpool:"GET /HARPApiExternal/api/ResearchSummaries?datePublishedFrom=2015-01-01&datePublishedTo=2015-12-31&updatesFilter=1 HTTP/1.1" 500 661

**Comment by BenGosub** [comment]
@roll I have the data, you can give me further instructions.

**Comment by BenGosub** [comment]
@roll, @pwalsh 

I've created fields for all records and the complete data dictionary in the collector as it is defined in the API guide document.

What is the Last_Updated date string used for? Do I need to keep this manually?

I see @roll uses record = Record.create(url, data) - What is the URL argument here for? Do I need to use the current endpoint I am getting data from?

Also, you define a spider when parsing ZIP files, I assume I need to define a spider in the same way so that the records will be written to warehouse? Should I do it as:

spider = type(b'Spider', (object,), {'conn': conn})
pipeline = base.pipelines.Warehouse()
pipeline.open_spider(spider)

and then for every record:
pipeline.process_item(record, spider)

RE: Write the logic to deal with the API restrictions (day range for queries)
- In the API documents it says the API works only on: "Monday, Wednesday, Thursday – between 6:00 - 8:00 am UTC", but I seem to be able to make calls right now, should the logic be mindful of this limitation? Besides this the only limit mentioned in the guide is that the API can return maximum of 365 days of data. 

Do I need to create the logic for collection inside the collector? I would write a While True loop that starts from today and goes back (because I don't know until when they have data) and each run of the collector it would first check the earliest datetime and start from there.

The API also returns modifications for each period. I assume that the latest modification should be kept in records. I've put "Application Id" as primary key and the latest modification for each Application ID should be kept in records, if we need every modification then Application ID cannot be used as primary key because there'll be duplicates.

Let me know if you have corrections, suggestions or additions :)

**Comment by roll** [comment]
@BenGosub 
- `Record.last_updated` is a key of your data model representing the when record was last updated on source. It could be `None` (used only for log message)
- `Record.create's url` argument - url of the source from where data's been collected. For API it could be url of the last query with pagination or something similar. 
- Yes to use handy `Pipeline.write_item` method we need this virtual spider (code with note in `fdadl`). I'll factor this `write-to-warehouse` functionality to separate function soon. I've just figured out that we could use `record-pipeline` functionlity without scrapy. So this approach not polished for now.

**Comment by roll** [comment]
About second part of question. For now we're not yet on continuous collecting workflow - https://github.com/opentrials/opentrials/issues/106 - but everything is ready to start to use it. All collectors will be running as docker services with `restart: always`.

So this collector could be the first working this way. It could be this steps:
- add to process `while True` cycle
- sleep OR exit after some sleep (like 1h) if we can't query the API because of schedule
- check latest `meta_updated` to understand from which date to query the API
- add reasonable timeouts between API calls

**Comment by roll** [comment]
@BenGosub 
Also based on gitter discussion to clarify. All credentials should go to `.env` file (it's in gitignore).
To read it from script you could use `os.environ` (will be added automatically from this file).

**Comment by roll** [comment]
@BenGosub 
Please rebase on `master` - now instead of ugly:
```
spider = type(b'Spider', (object,), {'conn': conn})
pipeline = base.pipelines.Warehouse()
pipeline.open_spider(spider)
pipeline.process_item(record, spider)
```
you could use just:
```
base.writers.write_record(conn, record)
```

**Comment by roll** [comment]
@BenGosub 
One other note)

Logging is used automatically on `base.writers.wirte_record` like `DEBUG:collectors.base.writers:Record - created: <ICDCM: B77 [2015-10-01]> - 9 fields`

But it will be a good practice to add some `INFO` message on `hra` collector level. See `fdadl` as example. Those messages could be:
- can't query because of schedule (sleep 1h and exit)
- collected 100 (200, 300 etc) records from `hra` 
etc

**Comment by BenGosub** [comment]
I am thinking about starting with latest data and going back by querying for 30 day periods in each request with 30s pauses between each request (is this reasonable?). 

On the beginning of every new restart the earliest date that has been stored in the Warehouse is needed so that the process can continue where it stopped the last time. I suppose this can be obtained if I log the value or store it in the database, do you support this kind of approach? I haven't seen DB queries in the code I've reviewed up till now. In the API fields there are two date fields `PublicationDate` and `UpdatedDate` but these are regarding the study and maybe the `DatePublishedFrom` used in the query string isn't the same... I assume the last used `DatePublishedFrom` should be logged or inserted into database and used as `DatePublishedTo` in the next restart in order to continue where it left.

The API query also uses a categorical query integer which indicates to query for
1. All Studies
2. Studies Published during the selected period
3. Studies Modified during the selected period

Do we need to keep every modification or only the latest?

**Comment by pwalsh** [comment]
@BenGosub we keep only the latest (ie: if a record was modified, we update the record in our db).

The other questions are very implementation specific, and should be discussed with @vitorbaptista and @roll

**Comment by roll** [comment]
@BenGosub 
About getting information about when collector has touched the `warehouse` last time - it's `meta_updated` field in database table.

Record internal fields (see `base.Record`):
```
meta_id = fields.Text()
meta_source = fields.Text()
meta_created = fields.Datetime()
meta_updated = fields.Datetime()
```

**Comment by roll** [comment]
FIXED
https://github.com/opentrials/collectors/pull/27
