### ISSUE TITLE
Trial detail view, sections with no data

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#131]
# Description

For many trials, we will have missing data for certain fields. This is true now and will be true as we add more data, and even as we improve our record matching and processing, there will still *always* be fields with missing data.

So, we need a nice, generic implementation of messaging when a field has missing data. 

### An example of current implementation

See how in this view there is missing data for:

- Conditions
- Treatments
- Conducted in

<img width="1280" alt="screenshot 2016-05-18 09 11 59" src="https://cloud.githubusercontent.com/assets/791678/15349089/9f9ae71a-1cd8-11e6-8f73-2bdaadb524db.png">

# Tasks

Needs thought, but we essentially want to say:

"We have no {THING} data for this trial. Help us by <a href="{LINK TO CONTRIBUTE}" title="contribute data">contributing data</a>."

- [ ] Solution for missing data in main content panel
- [ ] Solution for missing data in sidebar (can be same as main content panel)
- [ ] Implement in HTML for the Explorer and make a PR for the changes

**Comment by smth** [comment]
Contribute URL will need to be defined [here](https://github.com/opentrials/opentrials/commit/34ea752296a58b2804726fd6e0502581c2aaeae1#diff-aef0d9288fce72641c4b8450d62f4dfeR16). Unless it's different for each type of data, in which case it can be defined in each of [these macros](https://github.com/opentrials/opentrials/commit/34ea752296a58b2804726fd6e0502581c2aaeae1#diff-aef0d9288fce72641c4b8450d62f4dfeR32).
