### ISSUE TITLE
Links to related entities from the sidebar

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#136]
# Description

On a trial detail page, we link to "related entities" that we may have extra information on: persons, organisations, etc. We currently link from the "name of the thing" but that looks a little ugly when just applying basic link styling to it, especially as interlinking becomes more comprehensive as the database improves.

We need a more aesthetic link pattern for this scenario: possibly something that subtly suggests the thing is linked, and then on hover becomes more prominent. @smth up to you how and why and what :).

### Current implementation

<img width="282" alt="sidebar-links-implemented" src="https://cloud.githubusercontent.com/assets/791678/15350399/d425eb5c-1ce1-11e6-82bc-84e5a678aefd.png">

# Tasks

- [ ] Style for linking to entities from text in sidebar
- [ ] PR implementing in HTML
- [ ] ? Add to style guide.
