### ISSUE TITLE
Implement processor for HRA data

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#138]
# Description

Once we have HARP Research Summaries in the warehouse #128, we need to process it to match data onto trials, adjust database schemas as required, and push data forward to the API database.

# Tasks

- [x] read `processors` overview - https://github.com/opentrials/processors/blob/master/docs/overview.md
- [x] read contributing giude - https://github.com/opentrials/processors/blob/master/CONTRIBUTING.md
- [x] setup dev environment as written in contributing guide
- [x] clone and setup https://github.com/opentrials/api to run `npm run migrate` against development
`database` (second database, not a `warehouse`)
- [x] read a few `processors` examples like `nct`, `gsk` etc (when there are trial extractors)
- [x] copy https://github.com/opentrials/processors/tree/master/processors/nct processor as `hra` processor
- [x] update `processors.py` to work with `hra` table instead of `nct`
- [x] update `extractors.py` to extract data from HRA source (consult with othter processors examples, `base.writers` and @roll about dict keys extractors should return, related to #180)
- [x] run `make test` to lint and test code
- [x] run `hra` collector as `make start hra`
- [x] check database is filled correctly after `hra` processor run

@vitorbaptista @roll I just don't know the tech implementation details to write a proper task list for this. Please provide so @BenGosub can proceed after he finishes #128

**Comment by roll** [comment]
@BenGosub please ping me when you'll get data example from HRA so I'll be able to write this tasks

**Comment by BenGosub** [comment]
@roll I am getting status HTTP/1.1" 400 339 from their server. In the API documentation it says that the API works only on Monday, Wednesday, Thursday – between 6:00 - 8:00 am UTC. Status 339 is defined as: Delayed/Debugging. Status 400 is Bad Request. I think that my credentials are formatted correctly because when I use wrong credentials I get 401 (unauthorized).

**Comment by roll** [comment]
@BenGosub 
Thanks. I'll check with HRA representative.

**Comment by BenGosub** [comment]
Here's the output for clarity:

(.python) bozho@bozho-laptop:~/work/open_trials/opentrials-collectors$ make start hra
python -m collectors.base.cli hra
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): stage.harp.org.uk
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/logging/handlers.py", line 863, in emit
    self.socket.sendto(msg, self.address)
gaierror: [Errno -2] Name or service not known
Logged from file connectionpool.py, line 788
DEBUG:requests.packages.urllib3.connectionpool:"GET /HARPApiExternal/api/ResearchSummaries?datePublishedFrom=2015-01-01&datePublishedTo=2015-12-31&updatesFilter=1 HTTP/1.1" 400 339

**Comment by pwalsh** [comment]
This is the wrong issue for this discussion. Should be https://github.com/opentrials/opentrials/issues/128

**Comment by pwalsh** [comment]
Also see notes https://github.com/opentrials/opentrials/issues/163#issuecomment-220403757 about trial id matching.

**Comment by roll** [comment]
@BenGosub 
I've add one task to the first post - how to get `database` schema prepared.

**Comment by BenGosub** [comment]
@roll OK I see,  I will ping you if I have some questions.

**Comment by roll** [comment]
FIXED
https://github.com/opentrials/processors/pull/30
