### ISSUE TITLE
Add custom search query object to template context for all related entities

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#142]
# Description

In order for @smth to implement https://github.com/opentrials/opentrials/issues/124, we need some search info added to the template's context.

# Tasks

- [x] For each of person, organisation, condition and intervention detail views, add:
  - [x] a search result for the object being requested, with a hard limit of 10 results, as `searchResults`
  - [x] a search count of the objects, as `searchCount`
- [x] Tests as relevant

**Comment by vitorbaptista** [comment]
As an example of the search query for `Location == Japan`, see http://api.opentrials.net/v1/search?q=location:Japan

Instead of adding a `searchCount` element, I would simply add these results to the context and use `searchResult.total_count` in the view.

**Comment by pwalsh** [comment]
thx @vitorbaptista

**Comment by vitorbaptista** [comment]
Fixed by https://github.com/opentrials/opentrials/commit/598f843122caf922ea9eb13000017a81c307fd3c
