### ISSUE TITLE
Add Sources as a search parameters

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#145]
# Description

We have multiple source types. For each source type, we want to add a search field to select one or many, with a default of all.

Based on current data, we have two source types "Registry" and "Other" (PubMed, HRA, Epistemonikos). These need to be exposed as params for search queries, and via the search UI.

Search UI should be something like:

```
## Sources
### Registers
[multiselect, default all]
### Others
[multiselect, default all]
```
# Tasks
- [ ] API: Implement filter by sources + source types
- [ ] UI: Multiple select for registers, with default of all.
- [ ] UI: Multiple select for others, with default of all.

**Comment by pwalsh** [comment]
@roll @vitorbaptista is registry a "source" with type "registry"? If yes, is PubMed also a "source", with type "?"?

**Comment by roll** [comment]
Registry is a source with a type `register` and `Pubmed` is a source with a type `other`.

**Comment by pwalsh** [comment]
@roll thanks. In light of that, I updated the issue.

**Comment by vitorbaptista** [comment]
Maybe we should simply add a `Sources` select, with no distinction between registries and others? I understand that they're different things, but given that there're not many sources (and will not be), I think it's easier for the user to have one less option.

**Comment by pwalsh** [comment]
@vitorbaptista ok, perhaps. can consider when we implement.

**Comment by vitorbaptista** [comment]
Let's consolidate it on #589.
