### ISSUE TITLE
Add section to trial pages for identifiers

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#153]
# Description

Requires #152 

Trial identifiers are a crucial piece of information about a trial, but they are not exposed via our UI for trials.

The API has three fields that return identifiers:

- `primary_id`: the supposedly canonical ID for a trial, given by some external system
- `secondary_ids`: other IDs given by other systems to the same trial
- `id`: the internal identifier we use in OpenTrials 

# Tasks

- [x] Add a new section at the top of content area of the sidebar (under the buttons, before location) called "Identifiers"
- [ ] Add some little div thing that looks nice and appealing with a list in this order (so it will be a list from 2 to n items):
  - [x] OpenTrials ID: {ID}
  - [ ] Primary ID: {PRIMARY_ID}
  - [ ] SECONDARY_IDS: {SECONDARYS_IDS}
- Implement in HTML and submit PR

**Comment by smth** [comment]
I'm not seeing `primary_id` or `secondary_ids` in http://api.opentrials.net/v1/trials/05cc77ad-5575-4c04-9309-4c64d5144b07
What am I missing?

**Comment by pwalsh** [comment]
@vitorbaptista can you help here based on the current API that @smth has to work with

**Comment by vitorbaptista** [comment]
This data will only be added after https://github.com/opentrials/opentrials/issues/152 is done.

@smth Just so you're not blocked on that, you can consider that the IDs look like:

```
OpenTrials ID: 05cc77ad-5575-4c04-9309-4c64d5144b07
Primary ID: NCT1233243
Secondary IDs: ISRCTN2342342, FOO0000000
```

**Comment by smth** [comment]
OK, thanks. I've speculated a little and added these like so https://github.com/opentrials/opentrials/commit/59676c7f25a93c3a019b914dcd325847e6fe70c3#diff-aef0d9288fce72641c4b8450d62f4dfeR119

**Comment by vitorbaptista** [comment]
Fixed :+1:
