### ISSUE TITLE
Custom processor to get trial source count data to CSV

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#154]
# Description

For each trial, write a record of:
- ID
- SOURCE_COUNT (# of sources for that trial)
- PRIMARY_ID
- SECONDARY_ID{_1;_2;etc} - iterate over the ids to create columns
- {SOURCE_NAME} ("Yes" or "No") indicating if THIS source provided data.

Example:

```
ID | SOURCE_COUNT | PRIMARY_ID | SECONDARY_ID_1 | SECONDARY_ID_2 | EUCTR | HARP | ACTRN
{UUID} | 2 | A182 | B929 | | Yes | No | Yes
```
# Tasks
- [ ] Write the SQL query to get our required data from the warehouse.
- [ ] Write the [JSON Table Schema](http://dataprotocols.org/json-table-schema/) for the CSV we are creating.
- [ ] Write the [Data Package (Tabular Profile)](http://dataprotocols.org/tabular-data-package/) for the CSV we are creating (the JTS created above is the `schema` for our CSV resource).
- [ ] Target our S3 bucket, and then with a path/namspace of `adhoc` and a containing directory of `trial-sources` (so: `BUCKET_NAME/adhoc/trial-sources/`)
- [ ] In the directory, write:
  - [ ] The datapackage to `datapackage.json`
  - [ ] The CSV to `data.csv`
- [ ] Run the processor
- [ ] Tests

**Comment by pwalsh** [comment]
@vitorbaptista @roll this is the processor I was talking about in slack.

**Comment by vitorbaptista** [comment]
@pwalsh Is this still relevant?

**Comment by pwalsh** [comment]
OUT OF DATE.
