### ISSUE TITLE
Summary reports from EUCTR

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#157]
# Description

Some records on EU CTR have a summary report: https://www.clinicaltrialsregister.eu/ctr-search/trial/2010-019261-28/results

This does not seem to be covered in our extraction. We need to update our extractor for EUCTR for this (and possibly other?) fields of data, so we can then proceed with https://github.com/opentrials/opentrials/issues/156

# Tasks

- [ ] Update extractors to deal with the summary report field (which, apparently, is always a pdf link)
- [ ] Do another check for any other fields we might be missing
- [ ] Run the EU CTR collector again: we want 100% coverage
