### ISSUE TITLE
UI/X design: iteration 1

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#19]
# Description

Core views for the main OpenTrials app. Prior work has been done, but we need to revisit according to style guide and current understanding of public-facing features.

# Tasks

- [x] Update style guide, if required
- [x] Home page with search
  - The original mock has the boxes for different user types. We dont want that now. All we want is:
    - The title, brief text to pitch the platform, and a nice large search box, with a very clear action for advanced search (assumption is that advanced search will be quite used by some researchers)
    - advanced search will open up a bunch of inputs, similar to prototype screenshot below. Here is a list of the inputs we definitely need (so you have an idea of how to design it based on size)
      - Free text (just free text input)
      - Conditions (free text, with suggest, can select multiple)
      - Interventions (free text, with suggest, can select multiple)
      - People (free text, with suggest, can select multiple)
      - Organisations (free text, with suggest, can select multiple)
      - Locations (free text, with suggest, can select multiple)
      - Dates (date picker range, with paired pickers)
      - Gender (dropdown selection)
      - Participant count (paired integer input, or some other for a range)
- [x] Trial Detail page
- [x] HTML implementations of above (can be included as elements with the style guide, or just as full pages with style guide, as you prefer)

# Original home page mock

![opentrials_03_home_01](https://cloud.githubusercontent.com/assets/791678/13770130/888e8806-ea8d-11e5-8e30-702ddbf2d2c5.png)

# Prototype with search filters

<img width="1280" alt="screenshot 2016-03-15 09 21 45" src="https://cloud.githubusercontent.com/assets/791678/13770395/62b6bfde-ea8f-11e5-99e8-62b137920b1e.png">

# Original trial page mock

![opentrials_03_researchersview_04](https://cloud.githubusercontent.com/assets/791678/13770143/a71be26e-ea8d-11e5-968d-a45c6c7f58c1.png)

# Prototype trial page

<img width="1280" alt="screenshot 2016-03-15 09 22 33" src="https://cloud.githubusercontent.com/assets/791678/13770407/7c06215a-ea8f-11e5-954c-9015a6f27d47.png">

**Comment by pwalsh** [comment]
DONE
