### ISSUE TITLE
Improve pubmed data collection and processing

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#200]
# Description

More publications could be collected from `pubmed` source. Collected publications could be better linked to trials.

# Tasks

- [x] collect mesh terms
- [x] human-readable source_url
- [x] fix updating publications starts_url logic
- [x] ~~use more smart method for generating start_urls (see below)~~
- [x] rebase `pubmed` collector on `controlled clinical trial"[Publication Type]` filter usage
- [x] add warenouse migrations for added fiels
- [ ] collect to `warehouse`  publications available for this filter

---

- [x] move `pubmed` linking logic for separate processor
- [x] create trials for all found ids
- [x] improve `pubmed` linking logic 
- [x] process `pubmed` against database
- [x] process `pubmed_linker` against database

---
> Idea how to generate start_urls: 
search for wildcarded `nct10[0-9]*`, `isrctn1[0-9]*` etc in all fields - we need some cycle algorithm here because max 600 identifiers could be used in one Pubmed search

**Comment by pwalsh** [comment]
@roll 

We need both Randomized Controlled Trial [Publication Type] and Controlled Clinical Trial [Publication Type], with each record tagged by type.

**Comment by pwalsh** [comment]
And, can you get a count of records per category after collection (ben is asking)/

**Comment by roll** [comment]
@pwalsh 
ok

**Comment by roll** [comment]
I think I could get a count even before collection:
- controlled clinical trial = 498611
- randomized controlled trial = 413029 (all are included to controlled clinical trials)

**Comment by roll** [comment]
@pwalsh 
@vitorbaptista 
Are we interested here on this stage on some probabilistic methods (like BenG was talking about)? If yes - I could add to `trials_publications` something like `match_type` and `probability` fields.

**Comment by vitorbaptista** [comment]
@roll Unless there're some easy wins, I wouldn't bother with it before we have a way to test and validate the matching algorithms.

**Comment by roll** [comment]
DONE
