### ISSUE TITLE
Processor for Epistemonikos data

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#210]
# Description

Once we have systematic reviews from Epistemonikos in the warehouse #211, we need to process it to match data onto trials, adjust database schemas as required, and push data forward to the API database.
# Tasks
- [ ] read `processors` overview - https://github.com/opentrials/processors/blob/master/docs/overview.md
- [ ] read contributing giude - https://github.com/opentrials/processors/blob/master/CONTRIBUTING.md
- [ ] setup dev environment as written in contributing guide
- [ ] clone and setup https://github.com/opentrials/api to run `npm run migrate` against development
  `database` (second database, not a `warehouse`)
- [ ] read a few `processors` examples like `nct`, `gsk` etc (when there are trial extractors)
- [ ] copy https://github.com/opentrials/processors/tree/master/processors/nct processor as `hra` processor
- [ ] copy https://github.com/opentrials/processors/tree/master/processors/base/processors/publication as base `review` processor
- [ ] update base `review` processors to work for reviews, write all found trial identifiers as a trial even there is no match in database
- [ ] update `processors.py` to work with `epistemonikos` table instead of `nct`
- [ ] update `extractors.py` to extract data from Epistemonikos source (consult with other processors examples, `base.writers` and @roll about dict keys extractors should return, related to #180)
- [ ] run `make test` to lint and test code
- [ ] run `epistemonikos` collector as `make start epistemonikos`
- [ ] check database is filled correctly after `epistemonikos` processor run

**Comment by pwalsh** [comment]
@vitorbaptista please check if anything else is required above. It is adapted from the similar issue written by @roll for HRA.

@roll I want to ensure that if we ID new trials from the Epistimonikos source that we write them as new trial records (same as related issue on PubMed). Anything we should add to task list to make that fact clearer?

**Comment by roll** [comment]
@pwalsh 
added a few tasks

@vitorbaptista 
What we should write for only-id trials? For now we have some not-null values like `public_title`.

**Comment by pwalsh** [comment]
@roll thanks.

**Comment by vitorbaptista** [comment]
@roll Considering that the `public_title` is the only field which might give us problems (so far), I'd say we use the identifier as a temporary title

**Comment by vitorbaptista** [comment]
Blocked because of #211

**Comment by pwalsh** [comment]
WONTFIX for phase I
