### ISSUE TITLE
Collector for Epistemonikos data

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#211]
# Description

Epistemonikos ( http://www.epistemonikos.org/ ) has systematic reviews for a range of clinical trials. These can be extracted, cached in our warehouse (what a collector does), and then later processed to match on trials and prepare for exposing via the public Database/API (what a processor does: has a distinct task https://github.com/opentrials/opentrials/issues/210).
## Existing collectors for API-based data sources

FYI if helpful to reference.
- https://github.com/opentrials/collectors/tree/master/collectors/icdcm
- https://github.com/opentrials/collectors/tree/master/collectors/fdadl
- https://github.com/opentrials/collectors/tree/master/collectors/icdpcs
# Tasks
- [ ] Read `collectors` documentation - https://github.com/opentrials/collectors#collectors (esp. how to write collector tutorials)
- [ ] Setup dev environment using contribution guide - https://github.com/opentrials/collectors/blob/master/CONTRIBUTING.md
- [ ] Read some `collectors` examples like `nct`, `pubmed` etc
- [ ] Implement `collect` interface to request _all_ systematic reviews data from Epistemonikos. Work could be started as a copy of any suitable existent collector
- [ ] Run local collection by `make start epistemonikos`
- [ ] Write logic for updating (when we have data in the table - see hra as example)
- [ ] Populate warehouse table with the data
- [ ] Write tests

**Comment by pwalsh** [comment]
@vitorbaptista please edit the issue above with any changes needed.

**Comment by roll** [comment]
High-level testing example - https://github.com/opentrials/collectors/blob/master/tests/test_hra.py#L17-L20

**Comment by vitorbaptista** [comment]
For whoever works on this: there's some WIP code in the collectors' [epistemonikos branch](https://github.com/opentrials/collectors/tree/epistemonikos). Feel free to ignore it if it doesn't help you.

**Comment by roll** [comment]
I'll take this card next (for the end of the week) if everyone is OK with it.

**Comment by vitorbaptista** [comment]
@roll I think your time is better spent on other issues. Whenever you finish your current tasks, just pick the next one from the `Ready for Analysis` column on our Waffle board.

**Comment by nightsh** [comment]
@vitorbaptista as you're the author of the WIP code, I assume you have an API token somewhere in your local `.env`? :)

**Comment by georgiana-b** [comment]
@vitorbaptista I looked over the data offered in their website and in the example API responses. As it turns out. they provide the same info Pubmed does.
For example [this is the Epistemonikos version](http://www.epistemonikos.org/en/documents/d04d4ee6977db4bd5f58f1aa3f5206a1dcab9a34) and this is the [Pubmed version](https://www.ncbi.nlm.nih.gov/pubmed/28075489) of the same review.

I knew Pubmed contains reviews since I worked on Cochrane reviews but I though we are not interested in these summarized versions of reviews since they don't include the risk of bias for each reviewed trial. If we are, we could just [filter by "Review" in Pubmed](https://www.ncbi.nlm.nih.gov/pubmed?term=Review%5Bptyp%5D) and get them all.

Having these said, am I missing something or we really shouldn't collect from Epistemonikos?

**Comment by georgiana-b** [comment]
So, collecting reviews from Epistemonikos for the purpose of creating [Risk of bias records](https://github.com/opentrials/api/blob/master/api/models/risk_of_bias.js) is not viable because we can't access the full body of the review which contains results for each trial.

However, they are doing a good job connecting systematic reviews to the "primary studies" i.e. `trials` that are reviewed in them, even manually. For example, for [this Cochrane review we processed](http://www.epistemonikos.org/en/documents/abc5704641bc96b3bab593c6307be1fde6a03f6a), they provide links to all 10 `trials` that were part of the review. So, we could use Epistemonikos in the future to link reviews with `trials` after we take the full review from somewhere else.

For now, I'm moving this to our Backlog.

**Comment by pwalsh** [comment]
WONTFIX for phase I
