### ISSUE TITLE
Improved deduplication system

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#240]
# Description

Based on current experience of data deduplication I could suggest some implementation improvements and strategies to use. I'll write it as tasks for the reading convenience but it's of course for a discussion (cc @vitorbaptista @pwalsh @benmeg).

Ideas highlights:
- use only identifiers for automatic matching
- improve querying duplicates implementation (facts system)
- use curators for matching records based on pre-processed similarity

# Tasks
- [ ] instead of `trials.facts` use `records.identifiers` (or indexable analogue) to search for the same trial records. Current implementation based on "stateful" `trials.facts` field should be replaced because of maintainability problems (e.g. after hra removing facts should be cleaned from hra strings etc).
- [ ] create processor and database table for calculation trials similarity. We could start with scientific titles match then follow with probabilistic and machine learning methods. As output table like `trial_id_1, trials_id_2, method, similarity, is_marked_as_matching, updated_by_user_id` (not real naming just to show the idea). Could be split for 2 tables etc.
- [ ] create processor for reading similarity table to dynamically merge/unmerge records based on user marked matches
- [ ] create some redirects table because trial pages could be merged at any time (saving history of dedup process is a thing to think about)

---
- [ ] move UI tasks to different issue after discussion
- [ ] create UI for similarity table - as similar records on trial page with ability to mark it as duplicate
- [ ] create UI for similarity table - as a list of similar record pairs ordered by similarity to match by users/curators. So some hired curators or enthusiasts could highly effective processing this list from top to bottom.

**Comment by pwalsh** [comment]
just to say all looks solid and well thought out, but passing on so @vitorbaptista can decide on way forward here.

**Comment by vitorbaptista** [comment]
Sounds great, @roll. Let's talk about it during the summit.

**Comment by nightsh** [comment]
@vitorbaptista @roll have you reached any conclusion with this?

**Comment by vitorbaptista** [comment]
@nightsh We weren't able to talk about it yet :/

**Comment by roll** [comment]
DONE
