### ISSUE TITLE
Expose license and attribution information via API and UI

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#281]
It should be possible to know the license and where the contents of each page come from. We already have the attribution data on the Trials page in the form of the "Sources" list, and in the API, where every Trial's Records have a `source` field pointing to where they come from. We're then missing license information.

@pwalsh Considering that our sources might use custom license (e.g. [EU CTR](https://www.clinicaltrialsregister.eu/disclaimer.html)), I wonder how we would show them to the user. Maybe it's enough to just point out where the data comes from (i.e. attribution)? We can then have a new page in OpenTrials where we list all our sources and link to their licenses (if they have one).

# Tasks

- [x] Add `url` and `terms_and_conditions_url` attribute to `sources` table
- [x] Find where the data's license is defined in each source, and change the corresponding collector/processor to add it to the `sources.terms_and_conditions_url` column. Same for `sources.url`.
- [ ] Create new "Terms and Conditions" page with the list of sources, their URLs and their license's URLs

# Data

```csv
id,url,terms_and_conditions_url
actrn,http://www.anzctr.org.au,http://www.anzctr.org.au/Support/Terms.aspx
euctr,https://www.clinicaltrialsregister.eu,https://www.clinicaltrialsregister.eu/disclaimer.html
fda,http://www.fda.gov,
fdadl,https://open.fda.gov,https://open.fda.gov/terms/
gsk,http://www.gsk.com,http://www.gsk.com/en-gb/terms-of-use/
hra,http://www.hra.nhs.uk,http://www.hra.nhs.uk/terms-conditions/
icdcm,https://www.cms.gov/Medicare/Coding/ICD10/index.html,
icdpcs,https://www.cms.gov/Medicare/Coding/ICD10/index.html,
ictrp,http://www.who.int/trialsearch/,http://www.who.int/ictrp/search/download/en/
isrctn,http://www.isrctn.com/,http://www.isrctn.com/page/terms
jprn,http://rctportal.niph.go.jp/en/,http://rctportal.niph.go.jp/en/agreement
nct,https://clinicaltrials.gov,https://clinicaltrials.gov/ct2/about-site/terms-conditions
pfizer,http://www.pfizer.com/research/clinical_trials,http://www.pfizer.com/general/terms
pubmed,http://www.ncbi.nlm.nih.gov/pubmed,https://www.ncbi.nlm.nih.gov/home/about/policies.shtml
takeda,http://www.takedaclinicaltrials.com/,http://www.takedaclinicaltrials.com/legal/terms
```

**Comment by roll** [comment]
some references:
- https://github.com/opentrials/collectors/tree/master/docs/collectors
- https://github.com/opentrials/registers/blob/master/data/registers.csv

**Comment by vitorbaptista** [comment]
@pwalsh Do you have enough information to answer https://github.com/opentrials/opentrials/issues/281#issue-167868711, or should we ask someone else? So far, I'm considering that the way to solve this issue is to create a "Sources" or maybe "Methodology" page describing where the data comes from and linking to the licenses on each.

**Comment by pwalsh** [comment]
I'd say attribution *and* link to license, from the trial page (and from the API).

Could be something like a simple section for "Attribution", like:

```
# Attribution
<p>
Data on this page is built from the following sources.
</p>
<ul>
{% for source in trial.sources %}
<li>{{ source.name }}: <a href="{{ source.license }}">License</a></li>
{% endfor %}
</ul>
```

**Comment by vitorbaptista** [comment]
@pwalsh Added the tasks to the first comment. I haven't added a task to change the actual Trial page because we already display all trial's sources there, so it felt redundant. This is unblocked now :+1:
