### ISSUE TITLE
Get set up with all current Cochrane schizophrenia data

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#307]
# Description

We've got a bunch of data from Cochrane. 

Ultimately, we want to match important data from here into the OpenTrials database. Some of this should be relatively easy: the data from the Access database(s) was ported to Postgres last year, and we even made a prototype app around it. 

However, there is other data in RM5 files (an XML-based format), which we have not used much ( @danfowler knows a bit about the data though ), but potentially has the most interesting info in it.

Our short term goal is to get some of this data matched, in the OpenTrials database, onto things we know from PubMed, and other trial data.

## Sources

I've sent an email with lots of text and links to data. That provides context. Here are the actual links that are of relevance, and therefore you should start by getting all this data on your local machine:

- https://www.dropbox.com/sh/42w38vkscjgy8tt/AADW50Z42h3qlEU9t2_xxXD9a?dl=0
  - software to read and generate RM5: http://tech.cochrane.org/revman/download
- http://opentrials-prototype.herokuapp.com ( passcode `OPENTRIALS2015`; source https://github.com/opentrials/opentrials-early-poc )
- The psql database for the above app: https://drive.google.com/drive/folders/0BzgXxxfN_IbDfmYxQVFRR1lVNnJ5ejNvQlRZZDVGbDRrY19VRmJ0QndrMTV4ZnpNU1hndjA

# Tasks

- [x] Get the data on your local machine
- [x] Build a basic understanding of this data, and how it relates to OpenTrials
  - [x] Initial call with @roll who worked with some of the data
  - [x] Initial call with @danfowler who worked with the data, and knows a bit about the RM5 data
  - [x] Initial call with @jessflem to learn what she has done with the data recently, and what we want to get out of this data in the short term (i.e.: **in the next 2-3 weeks**)

@georgiana-b this is a time critical set of tasks - this issue and the ones that follow, so please contact these people and start talking to them ASAP.

@danfowler pls help onboarding @georgiana-b but ensuring I'm provided all the data links above, and contact her directly if not.

**Comment by georgiana-b** [comment]
The analysis is contained in #308 so I think this issue can be closed.
