### ISSUE TITLE
Add new document type "CSR Synopsis"

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#330]
Following the question on #312. We'll also need to move all our current documents marked as `csr` to be `csr_synopsis`.

# Tasks

- [x] Add the new `csr_synopsis` document type to the API (you'll need to add a migration and change the `swagger.yaml` at minimum)
- [x] Add the new `csr_synopsis` to the Explorer (add to `presenters/trial.js` and the data contributions page)
- [x] Fix the contrib processor and `processors/base/config.py` to use `csr_synopsis` instead of `csr`.

**Comment by roll** [comment]
PRs LGTM
