### ISSUE TITLE
Not all FDA drugs applications are available in FDA's Drug Labels

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#361]
On the `fda_dap` collector, we only add a new file if there's an existing `intervention` with the same `fda_application_number` as it. My expectation was that, given that the `fdadl` collector/processor creates interventions for all drug labels taken from FDA's data dump, there would be no drug without a corresponding intervention. Unfortunately, that's not the case, maybe because the labels are only for approved drugs.

Also, there're many interventions with the same FDA application number. This is because of different branding. This will require a few changes in our DB schema to handle correctly, mainly we'll need to create a new `fda_applications` table which will have the drug name, active ingredients and organisation. Then the `fda_approvals` and `interventions` must be changed to reference it.

# Tasks

- [x] Remove "intervention_id" from "fda_approvals"
- [x] Add "fda_application_id" to "fda_approvals"
- [x] Rename "interventions" fda_application_number to fda_application_id,
  referencing "fda_applications.id"
- [x] Save the drug's name, active ingredients and company name on "fda_dap"
  collector
- [x] Create "fda_applications" and "organisations" on "fda_dap" processor, linking
  the "fda_approvals" to "fda_applications" instead of "interventions".

**Comment by vitorbaptista** [comment]
Fixed
