### ISSUE TITLE
Link to research summaries in HRA website

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#415]
Our HRA collector/processor uses their internal API to extract the data. This makes it much easier to write and maintain, but then our `source_url` points to the API url, not the human-readable url (e.g. https://stage.harp.org.uk/HARPApiExternal/api/ResearchSummaries instead of http://www.hra.nhs.uk/news/research-summaries/longterm-fu-study-of-botox-in-idiopathic-overactive-bladder-patients/).

# Tasks

- [x] Change the HRA `source_url` to point to the human-readable URL in the HRA website (e.g. http://www.hra.nhs.uk/news/research-summaries/longterm-fu-study-of-botox-in-idiopathic-overactive-bladder-patients/)
- [x] Create new "Research summaries" section in the trial page sidebar with a link to the HRA research summary named "NHS Health Research Authority (HRA)"
- [x] Don't display the publications with `source_id = 'hra'` in the "Publications" section in the trials page
