### ISSUE TITLE
Remove /stats endpoint

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#431]
It does some very heavy queries and has an ugly layout. We can't use it without some caching/optimization and design work. For now, let's remove it.

# Tasks

- [x] Remove the `/stats` endpoint from API's swagger definition file
- [x] Remove the `/stats` route from the Explorer
- [x] Make sure all tests still pass, including the Explorer with the updated Swagger definition (i.e. the one done during this issue)
