### ISSUE TITLE
Collectors: improvements

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#46]
### Base

- [x] remove `OPENTRIALS_` prefix from env vars?
- [x] ~~item - required fields (pk etc)~~
- [x] improve array, json fields
- [x] ~~sync with `database` on names of meta fields (created/updated/etc)?~~
- [x] rename `Item` to `Record` for consistency across the project?
- [x] replace json by jsonb (in migration it's already jsonb so it has to be synced with production manually!)
- [x] ~~rename mapper module? (name collision with high-level mapper)~~
- [x] deploy to tutum only on tags?
- [x] merge stacks because of stack quota on Tutum?
- [x] rename tables with prefixes `data_*`, `index_*` etc?
- [x] use native postgres `uuid` type
- [x] rename `meta_uuid` to `meta_id`  like in `api`?
- [x] ~~move logging setup from `settings` to dedicated module (may be custom `cli`)?~~
- [x] rename `migrations` to `warehouse`?
- [x] ensure migrations logging works?
- [x] rename pipeline `Database` to `Warehouse`?
- [x] ~~generalize extraction utils~~
- [x] ~~extract_data - slugify group?~~
- [x] ~~extract_text - remode hided nodes~~
- [x] ~~extract_data - option to use xpath~~
- [x] improve papertrail logging formatter (https://github.com/opentrials/opentrials/issues/86)
- [x] continuous collecting (https://github.com/opentrials/opentrials/issues/106)

### Concrete

- [x] actrn - fix attachements (#107)
- [x] isrctn - fix funders extract list logic (#107)
- [x] actrn - return timepoints? (#107)
- [x] euctr - fix isrctn_international_standard_randomised_controlled_trial_numbe (max 31 char postgres) (#107)
- [x] pubmed - discover mesh terms and keywords (#107)
- [x] pubmed - extract full text line when available (no link in XML file) (#107)
- [x] pubmed - use better search tech with wildcards `nct01[1-9]*, isrctn0[1-9]*` etc? (#107)
- [x] ~~pubmed - handle better structured abstracts (we can add headings)~~
- [x] nct - migrate 3 is/has_* to boolean
- [x] takeda/ pfizer -  no primary keys (migrations issue)
- [x] jprn - rebase on `extract_data`?

**Comment by roll** [comment]
FIXED
