### ISSUE TITLE
Processors: improvements

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#48]
### Base

- [x] remove `OPENTRIALS_` prefix from env vars?
- [x] check `facts` search uses index
- [x] add time checks for `mapper` stack - map only updated/created items (https://github.com/opentrials/opentrials/issues/105)
- [x] improve papertrail logging formatter (https://github.com/opentrials/opentrials/issues/86)
- [x] remove `trials_trialrecords` table because it's not a `m2m` relationship?
- [x] use some kind of `slug` to improve `Finder` system (now it uses `person.name` for example)
- [x] refactor `Finder`
- [x] move column creation to `api` migration
- [x] adjust extractor (registers) priorities
- [x] merge `links` and `facts`?
- [x] use `facts` analogue for things like `person.name` (and:`primary_facts` + or:`secondary_facts`)?
- [x] don't md5 while slugifying scientific_titles? 
- [x] ~~add periodic logger.info like scrapy does: `Translated 50 trials (at 50 trials/min)` (speed is missing)~~
- [x] merge records on entity entries? (https://github.com/opentrials/opentrials/issues/103)

### Concrete

- [x] all - fix `extractors` todos with additional `scraper` work (https://github.com/opentrials/opentrials/issues/104)

**Comment by roll** [comment]
FIXED
