### ISSUE TITLE
Expose FDA applications and documents in our API

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#499]
They should follow the usual REST pattern (e.g. `/fda_applications` returns all applications, `/fda_applications/<id>` returns a specific one). This will also require pagination. Keep the return structure similar to our `search` interface (i.e. having a `total_count`, elements in `items`, accepting `page` and `per_page` parameters and so on)

The API responses are:

```javascript
// /fda_applications
{
  total_count: 100,
  items: [
    {
      id: 'application_id',
      url: 'http://api.opentrials.net/v1/fda_applications/application_id',
      drug_name: 'drug_name',
      active_ingredients: 'active_ingredients',
      organisation: {
        id: 'organisation_id',
        name: 'Acme',
        url: 'http://api.opentrials.net/v1/organisations/organisation_id',
      },
      approvals: [
        {
          id: 'approval_id',
          supplement_number: 1,
          action_date: '2016-10-04',
          type: 'type',
          notes: 'notes',
        },
        // ...
      ],
    },
    // ...
  ],
}
```

```javascript
// /documents
{
  total_count: 100,
  items: [
    {
      id: 'document_id',
      url: 'http://api.opentrials.net/v1/documents/document_id',
      name: 'name',
      source_id: 'nct',
      trial: {
        id: 'trial_id',
        url: 'http://api.opentrials.net/v1/trials/trial_id',
      },
      file_id: {
        id: 'file_id',
        sha1: 'sha1',
        source_url: 'file_url',  // in the DB this is `files.url`, using a different name because we use "url" for url in the API
      }
    }
  ],
}
```

# Tasks

- [x] Create `/fda_applications` endpoint that returns the FDA applications with their FDA approvals as an array
- [x] Create `/fda_applications/<id>` that returns a single application
- [x] Create `/documents` endpoint that, apart from the documents' attributes, also returns its `file` metadata (but not its other related entities, like `source`, `trial`, and `fda_application`)
- [x] Create `/documents/<id>` that returns a single document
