### ISSUE TITLE
Diff reports across threaded trial records

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#50]
@pwalsh 

# Description

Clinical trial data is published in a range of places, including over multiple trial registers. It is a known issue that different publications can declare discrepant facts on a trial. When we have a set of threaded records, we want to run a "diffing" algorithm over the records and pull out these discrepancies as data points in their own right.

# Tasks

* [x] Write a diff algorithm for a set of threaded records
* [x] Store the results of such diffs. They are a property of the "ideal" model of the trial on which the records are matched
* [ ] Push this data forward from the warehouse to the main database/API

**Comment by pwalsh** [comment]
Hey @roll 

Ben gave me an example query that can be useful for him and some researchers. I think maybe you can run a query like this as part of this work when you start it, and just export the actual results (query statement + results) and share with Ben.

He asks:

* get results of a query which selects trials that appear in 1+ registers, that have discrepancies on study end date, and one of those is "no end date", meaning, no end date is recorded in that particular record. We'd want that query result. Further, it would be good to filter those results, based on results where match is on trial ID, and results with match based on scientific title

**Comment by roll** [comment]
@vitorbaptista 
I've rebased both PRs - so it's ready to merge. Please re-assign me if/when (to start processor for production after migration) other actions from me will be needed.

**Comment by vitorbaptista** [comment]
@pwalsh I extracted the report you described on https://github.com/opentrials/opentrials/issues/50#issuecomment-206537109 to #197, as we're closing this. It might be good to tag those requests in a specific label :+1:
