### ISSUE TITLE
Fix running linter

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#529]
We're running eslint as `eslint *.js **/*.js`, which looks correct but isn't actually testing anything. eslint has problems with globs. Even though there're workarounds, the best way is to change that to `eslint .` This will run eslint on everything in the local folder, excluding `node_modules` and `bower_components`. There're a few other folders we want to ignore as well. For that, we need to create a  `.eslintignore` file. For instance, in the API, the `.eslintignore` will look like:

> /coverage/**

The Explorer will be similar, but we might need to add some other folders. Depending if eslint ends up giving us too many headaches, we might also disable it in specific folders (like the tests folder), but ideally it would run in the whole codebase.
# Tasks
- [ ] Change the `lint` script in `package.json` to `eslint .`
- [ ] Create a `.eslintignore` file adding folders that we don't want to lint on (e.g. `/coverage/**`)
- [ ] Do the above for both API and Explorer
- [ ] Fix the errors

**Comment by nightsh** [comment]
Just tried that and looks like a longer quest than what I expected. Lots of stuff got piled up while the linter was MIA. Just a heads up in case anyone tries fixing it before I do.

**Comment by nightsh** [comment]
Writing down some thoughts on it, as follows.

So, the issue here is that `posttest` never gets to run because `npm test` fails "by design", thus breaking the chain where `posttest` is conditioned by `test` exiting green in order to run.

We usually don't have the S3 credentials in development, and for good reasons. However, not having them breaks two of the tests and the whole suite goes down with them.

Proposed solution should somehow revolve around either not running certain tests when credentials for them are not provided, or figure out a way to send valid, but "development only" S3 creds in this particular case. I didn't find anything, but I assume there's a way to mock the service and that's probably supported by AWS already? Need a little bit more research.

**Comment by vitorbaptista** [comment]
@nightsh Could you link to these tests?

**Comment by nightsh** [comment]
Sure, here they are:

https://github.com/opentrials/opentrials/blob/master/test/agents/s3.js#L29
and
https://github.com/opentrials/opentrials/blob/master/test/agents/s3.js#L58
