### ISSUE TITLE
Expose additional fields of data to the advanced search form

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#55]
# Description

Search is an important pathway to data exploration, and search queries will become a more important aspect of our data structure in the future ([see user stories in section a](https://github.com/opentrials/docs/blob/master/docs/extras/user-stories/index.md#a-exploring-the-database)).

# Tasks

- [x] Conditions (free text, with suggest, can select multiple)
- [x] Interventions (free text, with suggest, can select multiple)
- [x] People (free text, with suggest, can select multiple)
- [x] Organisations (free text, with suggest, can select multiple)
- [x] Locations (free text, with suggest, can select multiple)
- [x] Dates (date picker range, with paired pickers)
- [x] Gender (dropdown selection)
- [x] Participant count (paired integer input, or some other for a range)
- [x] Published results (boolean)

**Comment by vitorbaptista** [comment]
The API and web site parts are done. The database for gender and published results isn't populated yet (depending on #84).
