### ISSUE TITLE
Stub out pages for relational entities

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#57]
# Description

We'll eventually build out views on a range entities related to trials. Even without proper design and ux treatment, it is good to flesh these out now as the basis of a navigational experience so we can iterate on design.

Do not worry about design: just stub out in the basic template, and throw out a list of key: value for whatever we have for that object.

# Tasks

* [x] Condition detail page
* [x] Intervention detail page
* [x] Person detail page
* [x] Organisation detail page 
* [x] From all instances of these entities on a Trial page, link out to the entity instance page
* [x] Basic functional tests

**Comment by vitorbaptista** [comment]
Which data would be in each of those pages? The actual entities have very little data on the DB, mostly just a `name`.

**Comment by vitorbaptista** [comment]
Idea: When clicking on an entity (say a location), we could send the user to the search page with that location in the filters.

**Comment by pwalsh** [comment]
Ok so for data - right now we only have names, but we will have full recently records for many things as we integrate data sources. The pages themselves can also help serve as calls to action to contribute data, not to mention potential seo benefits to capture search queries related to things like principal investigators, funding organizations and so on. So, it is quite important to flesh out the information architecture of the site.

About using the search results, I see where you are coming from. I'm -1 at the moment for reasons mentioned above though. Open for discussion though for sure.

**Comment by vitorbaptista** [comment]
Shall we wait until we have some data, then? I mean, I'm happy to create the pages, but they'll be empty with just the entity's name.

**Comment by pwalsh** [comment]
If you don't mind, I'll feel better if we do this now. It also means we are stubbing out the rest API which I'll also be happy about.

Is that ok?

**Comment by vitorbaptista** [comment]
OK, will do.
