### ISSUE TITLE
Remove dead code and data

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#573]
There's some dead code on the Explorer that we're not using anymore. Review our code and remove them. We can always go back to our git history if we ended up needing something.

# Tasks

- [x] Remove `records.source_data` from the DB
- [ ] Remove records page (e.g. https://github.com/opentrials/opentrials/blob/master/views/trial-record.html and https://github.com/opentrials/opentrials/blob/2f8abde37faaa0bbc574a8a77bf8bb9072a2b788/handlers/trials.js#L24-L40)
- [ ] Remove publications handler/UI
- [ ] Review every view and handler to see if it's used. Remove the ones that aren't.

**Comment by georgiana-b** [comment]
I noticed we have [some outdated documentation on database structure](https://github.com/opentrials/api/tree/master/docs).
@roll Do you remember what was the idea behind those docs? Isn't the up to date [schema described in swagger](https://api.opentrials.net/v1/docs/) enough?

**Comment by roll** [comment]
@georgiana-b
It has been created even before swagger. Should be removed I suppose

**Comment by georgiana-b** [comment]
Closed via opentrials/opentrials#617, opentrials/processors#97, opentrials/api#133
