### ISSUE TITLE
Add unique constraint to "records.source_url"

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#602]
On #532 we found a few records with repeated `source_url` values, and found out that was a bug. We then added a functionality to the `record_remover` processor to remove trials with the same `source_url`. Now we need to make sure that doesn't happen again by adding a unique constraint on that table. After that's done and tested, we can open a new issue to remove the then-useless functionality from `record_remover`.

# Tasks

- [x] Investigate if we still have records with repeated `source_url` in our database.
- [x] If we still have bad data in our DB, find why they were created, fix the bug and run the `record_remover` processor to clean our DB
- [x] Add a unique constraint on `records.source_url`
- [x] Remove the logic on removing records with duplicated `source_url` from the `record_remover` processor, as with the constraint we'll guarantee that this will never happen

**Comment by georgiana-b** [comment]
According to [this query](https://query.opentrials.net/queries/159/source#table) we still have duplicated EUCTR records. I think they were caused by [this change in collectors](https://github.com/opentrials/collectors/commit/66a274dfb34be029e4515cbe27bc436e3169d897). Because `eudract_number` was the primary key of `euctr` table in warehouse, when it was altered, a new `euctr` record without "EUCTR" in the identifier was created instead of updating the existing ones. Ex: [these 2 `euctr` records](https://query.opentrials.net/queries/160/source).
 Since [this commit](https://github.com/opentrials/processors/commit/cea8cc46628f491a80103200a55e68936410db33) both versions of identifier can be handled so this problem should not appear anymore and it's safe to remove duplicates both from `warehouse` and `opentrials` dbs.

**Comment by georgiana-b** [comment]
Fixed by above pull requests.
