### ISSUE TITLE
Setup Kong for our API

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#605]
Kong gives us many benefits, like API keys, stats collection, rate limiting, and others.

# Tasks

- [ ] Discover how to save our Kong configuration in our repository (there's a tool for that, but forgot its name)
- [ ] Enable the rate limiting plugin
- [ ] Document how to deploy it locally (link to existing docs as much as possible, to we can focus on the specifics of our project)

**Comment by nightsh** [comment]
Moving it to blocked for now, until we deal with the current infrastructure tasks – Kong deployment depends on how we do that.

**Comment by pwalsh** [comment]
covered elsewhere
