### ISSUE TITLE
Allow users to authenticate and have roles (permissions)

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#62]
# Description

Users need to be able to authenticate with the system, so that users can perform certain actions. Authenticated users need to be able to have roles, where each role relates to a flat permissions level (no granular permissions logic). Our use cases currently require three roles:

- `normal`
- `curator`
- `administrator`

No logic needs to be added on these roles at present, except that users will get a default `normal` role, and core developers can escalate a user's role to curator or developer by directly manipulating the database.

See the user stories related to [exploring data](https://github.com/opentrials/docs/blob/master/docs/extras/user-stories/index.md#a-exploring-the-database) and [curating data](https://github.com/opentrials/docs/blob/master/docs/extras/user-stories/index.md#b-contributing-and-curating-data) for some use cases related to users.

I ( @pwalsh ) do have a very specific idea of implementation in mind, based on many apps I've done with this implementation. We implement it in [OpenSpending](https://github.com/openspending/os-conductor/tree/master/conductor/blueprints/authentication), and it goes like this:

- Only oauth by existing providers (google is enough for now)
- All data comes from the provider, we essentially "cache" what we need (user name, etc) in a user table
- Client apps (like the explorer) get [JSON Web Tokens](https://jwt.io) with a payload of user identity info, and also info on expiring the token

Also note that the design by @smth for OT is based on the design in he new OpenSpending for users (in turn, based on the details of this implementation).

In other [OKI code](https://github.com/okfn/opendatacensus/blob/master/census/routes/utils.js#L22), we've used [Passport.js](http://passportjs.org) for user auth (albeit without JWT, and the full client-server interaction we use in OpenSpending and here)

# Tasks

- [ ] API methods to authenticate
- [ ] User gets a default role on first login
- [ ] Server returns JWT tokens for use by client apps
- [ ] Tests

**Comment by vitorbaptista** [comment]
Instead of implementing authentication on the API ourselves, I was thinking on trying something like [Kong](https://getkong.org), [Tyk](https://tyk.io) or some other API management project. It might me more difficult to setup upfront, but they provide lots of functionalities that we'll need sooner or later (rate-limiting, caching, etc...)

_Disclaimer: I have no experience with either tool_

Regardless of that, we'll probably need to implement authentication on the opentrials side as well for things like following trials, saving searches, etc. I don't think they should be implemented on the API level.

**Comment by pwalsh** [comment]
I don't know enough about these options to say. Conceptually, I love the idea as Kong marketing presents it.

Some concerns are if the open source version is crippled in ways that might bite us, and if it is easy to hook in our own logic, for example, our use cases around user roles. Also, do we fully host our own Kong gateway, or is it always via some centralized service of theirs?

@rollyour thoughts too?

**Comment by pwalsh** [comment]
Also, things like saving searches, what do you mean when you say authz related to that may not be implemented at the API level? Can you describe an alternative as you currently see it?

**Comment by vitorbaptista** [comment]
I don't know more about Kong or Tyk to say. It would be good to do a spike to see if they would help us.

About the saving searches, I was thinking that the API level will have just the core functionalities like searching, showing data, maybe uploading data (maybe not). All the rest, like saved searches, would be on the OpenTrials level. This would require another database and the issues that come with it, but it makes development simpler and allows the API-level to be leaner.

**Comment by pwalsh** [comment]
I see what you mean about saving that data to a different DB. I think (as I mention here https://github.com/opentrials/opentrials/issues/75#issuecomment-206397179) that essentially, we only read from the API db, and we write to the warehouse DB. Whether we do the writes with a different API ... I think you and @roll can decide what feels best.

**Comment by pwalsh** [comment]
@vitorbaptista also, about the spike: sure, go for it when you get here. 

But when you do it, let's have joint discussion with you, myself and @roll before we commit to it.
