### ISSUE TITLE
Disable autocomplete feature for everything except "locations"

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#651]
The autocomplete results are messy because the underlying data is messy, so they confuse more than help. The exception here is for location information, as we're normalizing it on https://github.com/opentrials/processors/pull/102.

# Tasks

- [x] Convert conditions, interventions, people and organisations filters to regular text inputs (rename their label to singular)
- [x] Change the Swagger file to allow autocomplete only on `location`
- [x] Change the indexers to index only locations

**Comment by nightsh** [comment]
We also need to adjust the search a bit. If we don't autocomplete anymore, this will lead to a world of typos, so fuzzy search should be default for all of them (I just did a search for condition "enrgy intake" and got me nothing, while "energy intake" has results).

**Comment by vitorbaptista** [comment]
Sure, but we can handle that issue separately, as it involves the whole search infrastructure

**Comment by nightsh** [comment]
Opened an issue for it, so we can now focus on this one.

**Comment by georgiana-b** [comment]
Closed via opentrials/api#154 and opentrials/opentrials#719.
