### ISSUE TITLE
It should be possible to have unknown trial status

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#653]
# Tasks

- [x] Create a migration to add `unknown` to the enumeration for `trials.status` and `records.status`
- [x] Change Pfizer processor extractor to set status as `unknown` when original status is `Unknown`
- [x] Add `unknown` status to possibilities in Swagger file
