### ISSUE TITLE
Add filter for registered VS unregistered trials

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#655]
For now, unregistered trials are trials where `source_id == pubmed`, but in general that's a trial which source's type isn't `registry`. In the future it could come from other sources (FDA, for example).

# Tasks

- [x] Create virtual attribute on Trial `is_registered` that returns `source_id !== 'pubmed'`
- [x] Update swagger file definition
- [x] Create filter on Explorer that searches for registered, unregistered or all trials
