### ISSUE TITLE
General cleanings and refactoring on our collectors/processors deployment

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#673]
We're now using Airflow which, at first, was deployed to our Kubernetes cluster. That didn't work out very well, so we're moving it to Docker Cloud. This issue aggregates many different tasks related to this move and from moving out of Docker Cloud into Airflow.

# Tasks

- [x] Remove Docker Cloud from processors/collectors
- [x] Setup Docker Hub to automatically build the processors/collectors containers
- [x] Move the containers to the `opentrials` organisation (so we'll have `opentrials/collectors` instead of `okibot/collectors`)
- [x] Configure our DNS to point to the servers on Docker Cloud
- [x] Add Docker Cloud's Stackfile to opentrials-airflow repository

**Comment by vitorbaptista** [comment]
This is only missing setting up CloudFlare which, for some reason, I've been unable to do. After this is merged, we also need to remove the (now unused) variables from Travis.

**Comment by vitorbaptista** [comment]
Fixed
