### ISSUE TITLE
Interfaces to add data

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#69]
# Description

Requires https://github.com/opentrials/opentrials/issues/68

Users can add data to the system. This data can be associated with a known trial, or not. See here for data structure info and more general context https://github.com/opentrials/opentrials/issues/68

# Tasks

- [x] Implement interactions on trial detail pages
- [x] Add a new page "Contribute Data" that implements the upload data form, without the context of a trial (don't worry if design is not perfect)
- [x] Above two tasks require success/fail interactions in front of user:
  - [x] Can add if not authed
  - [x] Feedback if file upload failed
  - [x] Feedback if file upload successful
- [x] Add a link to the "Contribute Data" page from the footer
- [x] functional tests as relevant
