### ISSUE TITLE
Interfaces to view and assess user-contributed data

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#70]
# Description

Requires https://github.com/opentrials/opentrials/issues/71

Users with either role `curator` or `administrator` need to be able to authenticate and access a view that shows all user contributed data. There is no existing design for this view, but that is ok. The main thing for this stage is to provide a simple way to allow these users to perform the following tasks:

- See data contributed manually by users
- Mark this data as accepted or rejected
- Add comments on the contribution

This set of tasks implements [user story B6](https://github.com/opentrials/docs/blob/master/docs/extras/user-stories/index.md#b-contributing-and-curating-data).

Note that this set of task does not try to handle what happens after data is accepted or rejected. We will have a manual process after this point for some time, and there is no need to write code for it at this stage.

# Tasks

- [x] When a user of with role `curator` or `administrator` is logged in, show an additional top-level menu item: "New data"
- [x] Create a new view for "new data" that is only accessible to authenticated users with role `curator` or `administrator`
- [x] On the "new data" view, show a list of contributed data (quantity of contributed data will be small for quite some time, so put no effort into search/filter etc on the list, just order by the timestamp of when the data was added)
  - User name
  - Date
  - Link to record for the contributed data
  -  Indicator if the contribution has been reviewed or not
- [x] The detail view for a record of contributed data is also only accessible to `curators` and `administrators`
- [x] The detail view for a contributed data record has the following elements
  - [x] User name
  - [x] Date
  - [x] Associated Trial ID (link from it to the actual trial detail page)
  - [x] Link(s) to contributed data sources (so this user can download these sources for inspection)
  - [x] A form to enter assessment details
    - [x] Boolean to "Reject" or "Accept" the data
    - [x] "Comments" text area to make comments on the data contribution
    - [x] Action to submit form
