### ISSUE TITLE
Don't use PubMed article's title as abstract on articles that have no abstract

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#712]
Our `publications` table requires a not null `abstract`, but there're a few PubMed articles that have no abstract.

# Tasks

- [ ] Remove the `not null` constraint on `publications.abstract`
- [ ] Update the Swagger file and API docs accordingly
- [ ] Remove code on the PubMed's processor that sets the abstract as the title if there's no abstract
