### ISSUE TITLE
Interfaces to use search queries

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#73]
# Description

Requires https://github.com/opentrials/opentrials/issues/72

Search queries can be used as starting points for exploring the database. Authenticated users can always access a list of their own search queries, and any visitor can browse a list of search queries by _most popular_ and _most recent_.

Implements user stories A4, A5 and A6: https://github.com/opentrials/docs/blob/master/docs/extras/user-stories/index.md#a-exploring-the-database
# Tasks
- [ ] When a user is authenticated, add "My Searches" to the top-level menu
- [ ] Add a view, accessible to the user only (ie: an account view) that shows this users search history
- [ ] Add a view accessible to all users called "Search Strategies", with a link to this view from the footer (for now...)
  - [ ] Show search queries ordered newest to oldest, with option to change order to most popular to least popular
- [ ] For both views of search query, have an HTML snippet like:
  - {QUERY} {REPRESENTED} {AS} {KEYWORDS}
    - Example: "Depression Prozac California 1988 1993"
  - Date created
  - Date last used
  - Clicking open a search result with that query made
