### ISSUE TITLE
Reindex ElasticSearch on Airflow after the data pipeline has completed

### ISSUE THREAD

**Issue by vitorbaptista** [opentrials/opentrials#734]
The last step of our data pipeline, reindexing, is executed manually for now by calling `heroku run:detached npm run reindex --app ot-api`. We want to automate it, so new data gets reindexed automatically.

# Tasks

- [x] Create HerokuOperator on Airflow that runs commands on Heroku
- [x] Make sure we ignore when previous HerokuOperators didn't run (see https://github.com/opentrials/opentrials/issues/714)
- [x] Make sure there's at most a single reindexing process running at any time
