### ISSUE TITLE
UI to allow crowd to vote on a record match yes/no

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#75]
# Description

Requires https://github.com/opentrials/opentrials/issues/76

See #76 for more info on this feature, and see [user stories B7, B8, B9](https://github.com/opentrials/docs/blob/master/docs/extras/user-stories/index.md#b-contributing-and-curating-data).
# Tasks

This task does not include design. Let's get the functionality working and then do a round with @smth 
- [ ] Expose a route and view, accessible to all users, to "check our data"
- [ ] This view takes an `entity` argument (see #76) to preselect the type of entity to be checked, and this selection corresponds to the API call that will be made to get data for the view
- [ ] The following elements are displayed:
  - [ ] The _record set_, being the matched objects. each record in the set should should key: value of all its fields from the source, as well as info like timestamps, source url and so on.
  - [ ] A form with the following fields
    - [ ] bool of "Yes, this match looks correct" or "No, this match looks wrong"
    - [ ] A comment field to let the user add comments
      - [ ] only allow the comment field if the user is authenticated. Provide an action to authenticate if the user is not, so that the comment field can appear  
- [ ] This view has a selector to change the entity being checked. This could be a section of the page at the top that says something like: "You are viewing some records we've matched for {ENTITY}s in the OpenTrials database." Where the word {ENTITY} could be a select box to change and choose between the available entities this API exposes (Trial, Person, Organization, Intervention and so on). Changing this triggers a reload of the data for the page, updating to suit the selection
- [ ] Tests

**Comment by pwalsh** [comment]
@roll @vitorbaptista note on this, I'm quite sure that while the frontend API will handle the data, it should be directly written to the warehouse database. I think that is the case for most actions that relate to processing and fixing data.

**Comment by roll** [comment]
@pwalsh 
One caveat of writing from `api` to `warehouse` - it will create a dependency between this two components. Now `api` does know nothing about `warehouse` and couldn't be broken because of any `warehouse` change.

If you considering the current situation (no dependency) as a valid PRO we could write from `api` to some other tables in `database`. `processors` could operate on both `warehouse` and `database` so there will not be any difference where this data stored.

**Comment by pwalsh** [comment]
@roll yes, sure, right. 

Happy for you and @vitorbaptista to discuss and decide on that. Any option works for me.
