### ISSUE TITLE
UI to see list of record matches in warehouse

### ISSUE THREAD

**Issue by pwalsh** [opentrials/opentrials#79]
# Description

Requires #76 and then #75

Curating users need to be able to see the results of record matching, and have useful filters over such results to target certain cases.

See #76 for more info on this feature in general terms, and see [user stories B7, B8, B9, B11](https://github.com/opentrials/docs/blob/master/docs/extras/user-stories/index.md#b-contributing-and-curating-data).

# Tasks

- [ ] Expose a route and view, accessible to all `curators`, called "Record Matching"
- [ ] Like #75, this view takes an `entity` argument (see #76) to preselect the type of entity to be checked, and this selection corresponds to the API call that will be made to get data for the view
- [ ] A list of record sets are displayed corresponding to the entity selected
  - [ ] Same controls to change entity as per #75
  - [ ] Filters for this list (really critical feature):
    - [ ] Show matched by type ( exact match, user match, probabilistic, and so on... cc @roll )
    - [ ] Show matches with user votes
    - [ ] Order by timestamp
- [ ] List should paginate
- [ ] Each record set on this list view links out to a dedicated page for the record set, where actions can be performed, as captured in https://github.com/opentrials/opentrials/issues/75
  - [ ] Snippet for a record set has some meta data about it (name of records, sources and so on)
- [ ] Tests
